Algoritmo "olaMundo"
// Função : Primeiro algoritmo
// Autor : Rodrigo Motta Mourão
// Data : 06/11/2018
// Seção de Declarações
Var
   msg: caractere //Cria a variável msg
Inicio
// Seção de Comandos 
   msg <- "Olá Mundo!" //Atribui "Olá Mundo!" à variável msg
   EscrevaL(msg, " Me Livrei da Maldição!") //Exibe o conteúdo da variável, seguido da mensagem entre parenteses e pula para a próxima linha
   Escreva("Fim!")
FimAlgoritmo
