Algoritmo "operadoresRelacionais"
// Função : Uso dos operadores relacionais
// Autor : Rodrigo Motta Mourão
// Data : 07/11/2018
Var
   A, B, C: Inteiro
Inicio
   A <- 2
   B <- 3
   C <- 5
   EscrevaL("A = ", A, ", B = ", B, "e C = ", C)
   EscrevaL("A>B? ", A > B)
   EscrevaL("B<C? ", B < C)
   EscrevaL("A+B = C? ", (A+B) = C)
   EscrevaL("A <= C-B? ", C-B <= A)
   EscrevaL("A^B >= C? ", A^B >= C)
   EscrevaL("C%A <> C? ", C%A <> C)
FimAlgoritmo
